<?php

/**
 * @file
 * Provides content authorship recording and display system.
 */

/**
 * Default Drupal implementation.
 */
define('CUSTOMAUTHOR_NODE_USER', 0);

/**
 * Another user, not the content owner.
 */
define('CUSTOMAUTHOR_OTHER_USER', 1);

/**
 * Other Author (plain text).
 */
define('CUSTOMAUTHOR_OTHER', 2);

/**
 * None.
 */
define('CUSTOMAUTHOR_NONE', 3);

/**
 * Implements hook_permission().
 */
function customauthor_permission() {
  return array(
    'change content owner' => array(
      'title' => t('Change the Content Owner of a node'),
    ),
    'change content author' => array(
      'title' => t('Change the Displayed Author of a node'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function customauthor_theme($existing, $type, $theme, $path) {
  return array(
    'customauthor_multiple_authors' => array(
      'variables' => array('authors' => array(), 'settings' => array()),
    ),
  );
}

/**
 * Implements hook_node_insert().
 */
function customauthor_node_insert($node) {
  customauthor_node_save($node);
}

/**
 * Implements hook_node_update().
 */
function customauthor_node_update($node) {
  customauthor_node_save($node);
}

/**
 * Saves the customauthor fields for a node that's being inserted or updated.
 */
function customauthor_node_save($node) {
  $settings = customauthor_node_type_settings($node->type);
  if ($settings['enabled']) {

    // When 'Save & Publish' is selected the node is saved twice but the second
    // time the customauthor field is empty and causes an overwrite.  This flag
    // denotes the sencond time workbench is saving the node so we skip
    // re-saving the customauthor data.
    if (isset($node->workbench_moderation) && !empty($node->workbench_moderation['updating_live_revision'])) {
      return;
    }

    $nid = $node->nid;
    $vid = $node->vid;

    $query = db_select('customauthor', 'oa');
    $query->fields('oa', array('nid', 'vid'));
    $query->condition('nid', $nid);
    $query->condition('vid', $vid);
    $exists = $query->execute()->rowCount();

    $primary_keys = $exists ? array('nid', 'vid') : array();

    // Set the default customauthor mode to node user.
    if (!isset($node->customauthor['mode'])) {
      $node->customauthor['mode'] = CUSTOMAUTHOR_NODE_USER;
    }

    $record = array(
      'nid' => $nid,
      'vid' => $vid,
      'mode' => $node->customauthor['mode'],
      'other_uid' => 0,
      'other' => NULL,
    );

    if ((int) $node->customauthor['mode'] === CUSTOMAUTHOR_OTHER_USER) {
      // If using multiple authors, do nothing, since multiple authors are
      // stored in a field.
      if (!$settings['multiple_authors']) {
        // Find `other_uid` from the provided string in `customauthor_other_user`.
        $account = user_load_by_name($node->customauthor['other_user']);
        $record['other_uid'] = $account->uid;
      }
    }
    elseif ((int) $node->customauthor['mode'] === CUSTOMAUTHOR_OTHER) {
      $record['other'] = $node->customauthor['other'];
    }

    drupal_write_record('customauthor', $record, $primary_keys);
  }
}

/**
 * Implements hook_node_load().
 */
function customauthor_node_load($nodes) {
  foreach ($nodes as $i => $node) {
    $query = db_select('customauthor', 'oa');
    $query->fields('oa', array('mode', 'other_uid', 'other'));
    $query->condition('nid', $node->nid);
    $query->condition('vid', $node->vid);
    $row = $query->execute()->fetchAssoc();
    $nodes[$i]->customauthor = $row;
    $nodes[$i]->customauthor['mode'] = (int) $nodes[$i]->customauthor['mode'];
  }
}

/**
 * Implements hook_form_alter().
 */
function customauthor_form_node_form_alter(array &$form, array &$form_state) {
  $type = $form['type']['#value'];
  $form['#customauthor'] = $settings = customauthor_node_type_settings($type);
  if ($settings['enabled']) {
    $node = $form_state['node'];

    $form['author']['name']['#title'] = t('Content Owner');
    $form['author']['name']['#description'] = t('The CMS user with permission to manage this content.');
    $form['author']['name']['#access'] = user_access('change content owner');

    $mode_selector = ':input[name="customauthor[mode]"]';
    $form['author']['customauthor'] = array(
      '#tree' => TRUE,
      '#weight' => $form['author']['name']['#weight'] + 0.5,
      '#access' => user_access('change content author'),
    );
    $form['author']['customauthor']['mode'] = array(
      '#type' => 'select',
      '#title' => t('Authored by'),
      '#options' => array(
        CUSTOMAUTHOR_NODE_USER => t('Content Owner (default)'),
        CUSTOMAUTHOR_OTHER_USER => t('Other Site User'),
        CUSTOMAUTHOR_OTHER => t('Other'),
        CUSTOMAUTHOR_NONE => t('No Author'),
      ),
      '#default_value' => isset($node->customauthor['mode']) ? $node->customauthor['mode'] : CUSTOMAUTHOR_NODE_USER,
      '#weight' => -10,
    );

    $form['author']['customauthor']['content_owner'] = array(
      '#type' => 'item',
      '#title' => t('Content Owner'),
      '#markup' => '<em>' . $node->name . '</em>',
      '#states' => array(
        'visible' => array(
          $mode_selector => array('value' => CUSTOMAUTHOR_NODE_USER),
        ),
      ),
      '#access' => !user_access('change content owner'),
    );

    $form['author']['customauthor']['other_user'] = array(
      '#type' => 'textfield',
      '#title' => t('Author'),
      '#description' => t('Search for a site user.'),
      '#maxlength' => 60,
      '#autocomplete_path' => 'user/autocomplete',
      '#default_value' => '',
      '#weight' => -1,
      '#states' => array(
        'visible' => array(
          $mode_selector => array('value' => CUSTOMAUTHOR_OTHER_USER),
        ),
      ),
    );
    if (isset($node->customauthor['other_uid'])) {
      $account = user_load($node->customauthor['other_uid']);
      $form['author']['customauthor']['other_user']['#default_value'] = $account->name;
    }

    $form['author']['customauthor']['other'] = array(
      '#type' => 'textfield',
      '#title' => t('Author'),
      '#description' => t('Enter a name to display as the author of this content.'),
      '#default_value' => isset($node->customauthor['other']) ? $node->customauthor['other'] : '',
      '#weight' => -1,
      '#states' => array(
        'visible' => array(
          $mode_selector => array('value' => CUSTOMAUTHOR_OTHER),
        ),
      ),
    );

    if ($settings['multiple_authors'] && isset($form[$settings['multiple_authors_field']])) {
      $form['author']['customauthor']['other_user'] = $form[$settings['multiple_authors_field']];
      $form['author']['customauthor']['other_user']['#states'] = array(
        'visible' => array(
          $mode_selector => array('value' => CUSTOMAUTHOR_OTHER_USER),
        ),
      );

      $form[$settings['multiple_authors_field']]['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_node_validate().
 */
function customauthor_node_validate($node, $form, &$form_state) {
  // Validate the "other_user" field, only if not using multiple authors field.
  if ($form['#customauthor']['multiple_authors'] && isset($form[$form['#customauthor']['multiple_authors_field']])) {
    $form_state['values'][$form['#customauthor']['multiple_authors_field']] = $form_state['values']['customauthor']['other_user'];
  }
  else {
    if (!empty($node->customauthor) && $node->customauthor['mode'] == CUSTOMAUTHOR_OTHER_USER) {
      $name = $node->customauthor['other_user'];
      if (!($account = user_load_by_name($name))) {
        form_set_error('customauthor][other_user', t('The username %name does not exist.', array('%name' => $name)));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function customauthor_form_node_type_form_alter(array &$form, array $form_state) {
  $node_type = isset($form['#node_type']->type) ? $form['#node_type']->type : '';

  $form['customauthor'] = array(
    '#type' => 'fieldset',
    '#title' => t('Custom Author'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
  );
  $form['customauthor']['customauthor'] = array(
    '#tree' => TRUE,
  );

  $settings = customauthor_node_type_settings($node_type);

  $form['customauthor']['customauthor']['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use Custom Author'),
    '#default_value' => $settings['enabled'],
  );
  $form['customauthor']['customauthor']['multiple_authors'] = array(
    '#type' => 'checkbox',
    '#title' => t('Allow multiple authors'),
    '#description' => t('Check to allow multiple authors (other than the default one) to be attached to a node'),
    '#default_value' => isset($settings['multiple_authors']) ? $settings['multiple_authors'] : 0,
    '#states' => array(
      'visible' => array(
        ':input[name="customauthor[enabled]"]' => array('checked' => TRUE),
      ),
    ),
  );

  // Gather a list of all user reference fields on node type for use as multiple
  // author field.
  $fields = field_info_instances('node', $node_type);
  foreach ($fields as $key => $field) {
    $field_info = field_info_field($key);
    if ($field_info['type'] == 'entityreference') {
      $options[$key] = $field['label'];
    }
  }
  $form['customauthor']['customauthor']['multiple_authors_field'] = array(
    '#type' => 'select',
    '#title' => t('Multiple author field'),
    '#options' => isset($options) ? $options : array('' => t('No reference fields available')),
    '#description' => t('Select the user reference field to use as multiple author field. If there are no user reference fields on this content type, then <a href="!url">create one</a>.', array(
      '!url' => url('admin/structure/types/manage/' . $node_type . '/fields'),
    )),
    '#default_value' => isset($settings['multiple_authors_field']) ? $settings['multiple_authors_field'] : 0,
    '#states' => array(
      'visible' => array(
        ':input[name="customauthor[multiple_authors]"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['#submit'][] = 'customauthor_node_type_form_submit';
}

/**
 * Submit handler for node type settings form.
 *
 * Fixes tree handling for nested variables.
 */
function customauthor_node_type_form_submit($form, &$form_state) {
  $node_type = $form['#node_type']->type;

  variable_del('customauthor_' . $node_type);
  variable_set('customauthor_' . $node_type, $form_state['values']['customauthor']);
}

/**
 * Implements hook_username_alter().
 */
function customauthor_username_alter(&$name, $account) {
  // Try to tell if this is a node that has customauthor.
  if (isset($account->customauthor)) {
    $settings = customauthor_node_type_settings($account->type);

    // If viewing other user with multiple authors, need to use a more complex
    // theming method, since multiple authors are stored within a field.
    // @see customauthor_preprocess_username().
    if ($account->customauthor['mode'] === CUSTOMAUTHOR_OTHER_USER && !$settings['multiple_authors']) {
      $other_user = user_load($account->customauthor['other_uid']);
      $name = $other_user->name;
    }
    elseif ($account->customauthor['mode'] === CUSTOMAUTHOR_OTHER) {
      $name = $account->customauthor['other'];
    }
    elseif ($account->customauthor['mode'] === CUSTOMAUTHOR_NONE) {
      $name = '';
    }
  }
}

/**
 * Implements hook_preprocess_username().
 */
function customauthor_preprocess_username(&$variables) {
  $variables['name'] = $variables['name_raw'];

  // Don't link to account if using custom author string or no author.
  if (isset($variables['account']->customauthor)) {
    $settings = customauthor_node_type_settings($variables['account']->type);

    switch ($variables['account']->customauthor['mode']) {
      // If viewing multiple authors, use a more complex theme.
      case CUSTOMAUTHOR_OTHER_USER:
        if ($settings['multiple_authors']) {
          $authors = field_get_items('node', $variables['account'], $settings['multiple_authors_field']);

          $variables['name'] = theme('customauthor_multiple_authors', array(
            'authors' => $authors,
            'settings' => $settings + array('account' => $variables['account']),
          ));
          unset($variables['link_path']);
          $variables['multiple_authors'] = TRUE;
        }
        break;

      case CUSTOMAUTHOR_OTHER:
      case CUSTOMAUTHOR_NONE:
        $variables['name'] = $variables['name_raw'];
        $variables['profile_access'] = FALSE;
        unset($variables['link_path']);
        break;
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function customauthor_preprocess_node(&$variables) {
  $node = $variables['node'];

  if (isset($node->customauthor) && $node->customauthor['mode'] === CUSTOMAUTHOR_NONE) {
    $variables['submitted'] = t('Submitted on !datetime', array('!datetime' => $variables['date']));
  }
}

/**
 * Helper function to tell if customauthor is enabled for a content type.
 *
 * @param string $node_type
 *   The valid node type to load settings for.
 *
 * @return bool
 *   TRUE if customauthor is enabled for node type.
 */
function customauthor_node_type_enabled($node_type) {
  $settings = customauthor_node_type_settings($node_type);
  return $settings['enabled'];
}

/**
 * Helper function to return customauthor settings for a node type.
 *
 * @param string $node_type
 *   The valid node type to load settings for.
 * @param bool $default_value
 *   The default enabled state for node type if not set. Defaults to TRUE.
 *
 * @return array
 *   Array of custom author settings.
 */
function customauthor_node_type_settings($node_type, $default_value = TRUE) {
  return variable_get('customauthor_' . $node_type, array(
    'enabled' => $default_value,
    'multiple_authors' => FALSE,
    'multiple_authors_field' => '',
  ));
}

/**
 * Theme callback for multiple authors.
 */
function theme_customauthor_multiple_authors($variables) {
  $settings = $variables['settings'];
  $authors = $variables['authors'];

  if (!$authors) {
    return '';
  }

  // Assume that authors are entity references, show linked entity labels.
  $field_info = field_info_field($settings['multiple_authors_field']);
  $entity_type = $field_info['settings']['target_type'];

  $links = array();
  foreach ($authors as $author) {
    $entity = entity_load_single($entity_type, $author['target_id']);
    $path = entity_uri($entity_type, $entity);
    $path['options']['html'] = TRUE;
    $name = '<span class="username-wrapper" about="'.$path['path'].'" itemprop="author" itemscope itemtype="https://schema.org/Person">';
    $name .= '<span itemprop="name">' . entity_label($entity_type, $entity) . '</span>';
    $name .= '</span>';
    $links[] = l($name, $path['path'], $path['options']);
  }

  // Add "and" to last element for more natural listing.
  if (count($links) > 1) {
    $links[] = ' and ' . array_pop($links);
  }

  // Only join by commas if there are more than two elements.
  return count($links) > 2 ? implode(', ', $links) : implode(' ', $links);
}
